- name: Intro to Ansible Playbooks
  hosts: 34.235.149.27
  gather_facts: no
  tasks:
   - name: Clone GitHub repository
     ansible.builtin.git:
        repo: "https://github.com/vamsimeduri/ansible.git"
        dest: "/tmp/ansible"
        version: master
